### ISSUE TITLE
如何上传一个指定URL的文件(比如图片)到Bucket

### ISSUE THREAD

**Issue by xhusky** [yunify/qingstor-sdk-java#14]
如题

```java
EvnContext evn = new EvnContext(ACCESS_KEY_ID, SECRET_ACCESS_KEY);
QingStor storService = new QingStor(evn);

Bucket.PutObjectInput input = new Bucket.PutObjectInput();
URLConnection connection =new URL(IMAGE_URL).openConnection();
InputStream inputStream = connection.getInputStream();

int len = connection.getContentLength();

input.setBodyInputStream(inputStream);
input.setContentType("image/jpeg");
input.setContentLength(len);
storService.getBucket(BUCKET_NAME).putObject(IMAGE_NAME, input);

```
小图片上传成功,大于几十k的图片都报错...
`
SEVERE: unexpected end of stream
com.qingstor.sdk.exception.QSException: Error Code: 0; Error Message: unexpected end of stream
	at com.qingstor.sdk.request.QSOkHttpRequestClient.requestAction(QSOkHttpRequestClient.java:160)
	at com.qingstor.sdk.request.QSRequest.sendApiRequest(QSRequest.java:109)
	at com.qingstor.sdk.service.Bucket.putObject(Bucket.java:3330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
`

**Comment by karoosnip** [comment]
你好，这个是urlInputStream有缓冲区，buffer read 的时候大小不是连续的；

我们会优化下，如果着急使用，可以先保存文件后通过putObjectInput.setBodyInputFile(); 上传

**Comment by xhusky** [comment]
@karoosnip 好的， 多谢。

**Comment by xhusky** [comment]
@karoosnip PR#16 好像修复了该问题, 但是maven仓库没有2.1.4的版本?

**Comment by karoosnip** [comment]
你好，maven的更新会稍微滞后点

**Comment by xhusky** [comment]
好的,一般周期多久?
