### ISSUE TITLE
分段上传的问题

### ISSUE THREAD

**Issue by hopeful0** [yunify/qingstor-sdk-java#4]
**分段上传问题**：

1.`uploadMultipartinput.setContentLength(size)`必须调用，否则会出现错误

```java
Exception in thread "main" java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.qingstor.sdk.request.QSOkHttpRequestClient.buildStorMultiUpload(QSOkHttpRequestClient.java:349)
	at com.qingstor.sdk.request.QSRequest.buildRequest(QSRequest.java:157)
	at com.qingstor.sdk.request.QSRequest.sendApiRequest(QSRequest.java:100)
	at com.qingstor.sdk.service.Bucket.uploadMultipart(Bucket.java:3264)
```
且size的值可以任意定义(上限未测试，下限4M貌似没用)：

* 当size大于等于file.length()时，会出现错误（这里等于时不应该出现错误,文件小于4M时未出现错误）
```java
Dec 07, 2016 2:52:43 PM com.qingstor.sdk.request.QSOkHttpRequestClient requestAction
SEVERE: unexpected end of stream
com.qingstor.sdk.exception.QSException: null; Action : null; Error Code: 0; Error Message: null)
	at com.qingstor.sdk.request.QSOkHttpRequestClient.requestAction(QSOkHttpRequestClient.java:159)
	at com.qingstor.sdk.request.QSRequest.sendApiRequest(QSRequest.java:102)
	at com.qingstor.sdk.service.Bucket.uploadMultipart(Bucket.java:3264)
	at Main.main(Main.java:404)
```
* 当size大于等于0小于file.length()-1时，通过List Multipart接口取得的分段信息中所得size于上传时设置的size相同，但是通过Get Bucket Statisticsbucket得到的bucket的空间占用为(size-23473)。
* 当size为-1时，通过List Multipart接口取得的分段信息中所得size为0。
* 当size小于-1时会得到`400:The request is invalid.
* 多个分段存在时通过Get Bucket Statisticsbucket得到的bucket的空间占用比所有分段size和小23473。

**上传图片测试结果**：图片内容未丢失。通过Head Object得到的Object的size正常。通过Get Bucket Statisticsbucket得到的bucket的空间占用比正常size小23473(byte)。
`

**关于分段上传的一些疑惑**：未测试实际上传的内容，但是对与分段上传的机制存在疑惑（忽略上诉问题）。分段上传允许设置inputfile和inputstream，应该是把分段过程交给sdk处理，但是仅要求设置contentlength，难以实现分段效果（缺少一个contentoffset），这还要开发者自己来进行分段。

**Comment by karoosnip** [comment]
你好，分段上传现在是根据 content length 和  part number计算content offset，来上传的；

如果size设置不正确，是应该要报错吧

**Comment by prettyxw** [comment]
> 关于分段上传的一些疑惑：未测试实际上传的内容，但是对与分段上传的机制存在疑惑（忽略上诉问题）。分段上传允许设置inputfile和inputstream，应该是把分段过程交给sdk处理，但是仅要求设置contentlength，难以实现分段效果（缺少一个contentoffset），这还要开发者自己来进行分段。

这里提到的 inputFile 或者 inputStream 属于 SDK 的高级接口，这类功能我们会在下一阶段陆续提供

**Comment by hopeful0** [comment]
@karoosnip 这个没有在文档中看到，所以测试的时候并不知道，希望能有文档说明清楚这个问题，否则很容易造成错误。我会再次测试这个接口。

但是`Get Bucket Statisticsbucke`给出的结果是不是有问题呢？

**Comment by karoosnip** [comment]
你好，我在帮助文档里加上了UploadMultipartInput；

你说的Statisticsbucke值不一致，这个我没有复现，估计要和其他同事一起看下，可以把你的操作过程发我邮件下么，karoo@yunify.com

**Comment by karoosnip** [comment]
Get Bucket Statisticsbucke给出的结果是不是有问题 ，目前后端已经fix

**Comment by hopeful0** [comment]
经过测试，问题已修复～
